--- #YAML:1.0
name:               User-Config
version:            0.01_00
abstract:           Handling the per-user configuration in multi-user applications
author:
    - Benjamin Tietz <btietz@cpan.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::Deep:  ~
requires:
    DBIx::Class:        ~
    HTML::FormHandler:  ~
    Moose:              2.02
    Net::LDAP:          ~
    Test::Deep:         ~
no_index:
    directory:
        - t
        - inc
        - t
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
